name: Bug report
description: Report a reproducible problem.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please include enough detail to reproduce.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Run ...
        2. Use flags ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, package versions, and execution backend.
      placeholder: Ubuntu 22.04, Python 3.11, pennylane 0.xx, pyscf 2.x, ...
    validations:
      required: true

