name: Feature request
description: Suggest an improvement or new capability.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What limitation are you trying to solve?
      placeholder: It is currently difficult to ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change you want.
      placeholder: Add/modify ... so that ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives or workarounds you evaluated.
      placeholder: I also considered ...
    validations:
      required: false

